version: '3'
services: 
  frontend:
    image: frontendapp:latest
    ports: 
      - "8081:80"
    networks: 
      - frontend
    deploy:
      replicas: 2
    depends_on: 
      - backend.api
    environment: 
      - BackendUrl=http://backend.api
  backend.api:
    image: backendapi:latest
    ports:
      - "8080:80"
    networks:
      - frontend
    deploy:
      replicas: 2
networks: 
  frontend:
    driver: overlay