version: '3'
services: 
  frontend:
    image: frontendapp:latest
    ports: 
      - "8081:80"
    networks: 
      - frontend
    deploy:
      replicas: 2
    depends_on: 
      - backend
    environment: 
      - BackendUrl=http://backend
  backend:
    image: backendapi:latest
    networks:
      - frontend
    deploy:
      replicas: 2
networks: 
  frontend:
    driver: overlay