version: '3'
services: 
  frontend:
    image: frontendapp:latest
    ports: 
      - "127.0.0.1:8001:80"
    networks: 
      - frontend
    deploy:
      replicas: 2
    depends_on: 
      - backend
  backend:
    image: backendapi:latest
    ports:
      - "8000:80"
    networks:
      - frontend
    deploy:
      replicas: 2
networks: 
  frontend: